---
bool success
string message
tgw_planner/MappingStats stats
string stats_json
uint32 occupied_points
uint32 free_points
uint32 static_points
uint32 dynamic_points
uint32 surface_points
uint32 traversable_points
uint32 blocked_points
uint32 forbidden_points
uint32 risk_points
