string input_dir
---
bool success
string message
bool loaded_voxel_evidence
uint64 voxel_count
uint32 occupied_points
uint32 free_points
uint32 static_points
uint32 dynamic_points
uint32 blocked_points
