string output_dir
---
bool success
string message
string occupied_pcd
string free_pcd
string static_pcd
string dynamic_pcd
string stats_json
uint32 occupied_points
uint32 free_points
uint32 static_points
uint32 dynamic_points
