tgw_planner_node:
  ros__parameters:
    pcd_file: ""
    map_frame: "map"
    map_id: "tgw_nav_map"
    robot_radius_m: 0.35
    robot_height_m: 0.50
    robot_length_m: 0.70
    robot_width_m: 0.43
    base_to_front_m: 0.20
    map_resolution_m: 0.20
    max_iterations: 250000
    max_marker_cells: 120000
    save_map_dir: ""

tgw_clicked_point_router_node:
  ros__parameters:
    click_mode: "none"
